name = "HelloWorld"
uuid = "517bdc27-85f7-4278-a6a9-ac9ee0730c03"
authors = ["Katharina Strebinger <kstrebin@uni-muenster.de>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
